name = "sso"
main = "src/index.js"
compatibility_date = "2026-06-08"
keep_vars = true

[[d1_databases]]
binding = "DB"
database_name = "openai_oidc_sso"
database_id = "cb274273-7299-4305-a1d9-a58253488e64"
